CLIENTE: 
CREATE TABLE clientes (
    cliente_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR2(100) NOT NULL,
    cpf_cnpj    VARCHAR2(20),
    telefone    VARCHAR2(20),
    email       VARCHAR2(100),
    data_cadastro DATE DEFAULT SYSDATE
);
CONDIÇÃO DE PAGAMENTO
CREATE TABLE condicoes_pagamento (
    condicao_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao   VARCHAR2(50) NOT NULL,
    parcelas    NUMBER NOT NULL,
    intervalo_dias NUMBER
);

NCM
CREATE TABLE ncms (
    ncm_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR2(10) NOT NULL,
    descricao VARCHAR2(200)
);
UNIDADE
CREATE TABLE unidades (
    unidade_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sigla VARCHAR2(10) NOT NULL,
    descricao VARCHAR2(50)
);
PRODUTO
CREATE TABLE produtos (
    produto_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao  VARCHAR2(100) NOT NULL,
    ncm_id     NUMBER NOT NULL,
    unidade_id NUMBER NOT NULL,
    ativo      CHAR(1) DEFAULT 'S',

    CONSTRAINT fk_produto_ncm FOREIGN KEY (ncm_id)
        REFERENCES ncms (ncm_id),

    CONSTRAINT fk_produto_unidade FOREIGN KEY (unidade_id)
        REFERENCES unidades (unidade_id)
);
PRECO / CUSTO
CREATE TABLE produtos_precos (
    preco_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id NUMBER NOT NULL,
    custo      NUMBER(10,2),
    preco_venda NUMBER(10,2),
    data_inicio DATE DEFAULT SYSDATE,

    CONSTRAINT fk_preco_produto FOREIGN KEY (produto_id)
        REFERENCES produtos (produto_id)
);
ESTOQUE
CREATE TABLE estoque (
    estoque_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id NUMBER NOT NULL,
    quantidade NUMBER(10,2) DEFAULT 0,

    CONSTRAINT fk_estoque_produto FOREIGN KEY (produto_id)
        REFERENCES produtos (produto_id)
);
VENDA
CREATE TABLE vendas (
    venda_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id NUMBER NOT NULL,
    condicao_id NUMBER NOT NULL,
    data_venda DATE DEFAULT SYSDATE,
    valor_total NUMBER(12,2),

    CONSTRAINT fk_venda_cliente FOREIGN KEY (cliente_id)
        REFERENCES clientes (cliente_id),

    CONSTRAINT fk_venda_condicao FOREIGN KEY (condicao_id)
        REFERENCES condicoes_pagamento (condicao_id)
);
ITEM DA VENDA
CREATE TABLE vendas_itens (
    item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venda_id NUMBER NOT NULL,
    produto_id NUMBER NOT NULL,
    quantidade NUMBER(10,2),
    valor_unitario NUMBER(10,2),
    valor_total NUMBER(12,2),

    CONSTRAINT fk_item_venda FOREIGN KEY (venda_id)
        REFERENCES vendas (venda_id),

    CONSTRAINT fk_item_produto FOREIGN KEY (produto_id)
        REFERENCES produtos (produto_id)
);
ORCAMENTO
CREATE TABLE orcamentos (
    orcamento_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id NUMBER NOT NULL,
    data_orcamento DATE DEFAULT SYSDATE,
    valor_total NUMBER(12,2),

    CONSTRAINT fk_orcamento_cliente FOREIGN KEY (cliente_id)
        REFERENCES clientes (cliente_id)
);
PEDIDO DE VENDA
CREATE TABLE pedidos_venda (
    pedido_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orcamento_id NUMBER,
    data_pedido DATE DEFAULT SYSDATE,

    CONSTRAINT fk_pedido_orcamento FOREIGN KEY (orcamento_id)
        REFERENCES orcamentos (orcamento_id)
);
CAIXA
CREATE TABLE caixa (
    caixa_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venda_id NUMBER NOT NULL,
    data_movimento DATE DEFAULT SYSDATE,
    valor NUMBER(12,2),

    CONSTRAINT fk_caixa_venda FOREIGN KEY (venda_id)
        REFERENCES vendas (venda_id)
);
FINANCEIRO
CREATE TABLE financeiro (
    financeiro_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venda_id NUMBER NOT NULL,
    parcela NUMBER,
    data_vencimento DATE,
    valor NUMBER(12,2),
    pago CHAR(1) DEFAULT 'N',

    CONSTRAINT fk_financeiro_venda FOREIGN KEY (venda_id)
        REFERENCES vendas (venda_id)
);
