CONDIÇÃO DE PAGAMENTO
CREATE TABLE condicoes_pagamento (
    condicao_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_condicoes_pagamento PRIMARY KEY,
    descricao VARCHAR2(50) NOT NULL,
    tipo_pagamento NUMBER(1) DEFAULT 1 NOT NULL
        CONSTRAINT ck_condicoes_tipo_pag CHECK (tipo_pagamento IN (0, 1)),
    forma_pagamento VARCHAR2(11) DEFAULT 'DINHEIRO' NOT NULL
        CONSTRAINT ck_condicoes_forma_pag CHECK (forma_pagamento IN ('BOLETO', 'DINHEIRO','CARTAO','CHEQUE','DUPLICATA','ACUMULATIVO'))
); OK 
CLIENTE: 
CREATE TABLE clientes (
    cliente_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR2(100) NOT NULL,
    data_nascimento DATE,
    status      VARCHAR(10) DEFAULT 'ATIVO' NOT NULL,
    cpf_cnpj    VARCHAR2(14),
    
    telefone    VARCHAR2(16),
    email       VARCHAR2(50),
    data_cadastro DATE DEFAULT SYSDATE NOT NULL,
    condicao_id NUMBER DEFAULT 1 NOT NULL,
    limite      NUMBER(10,2) DEFAULT 0 NOT NULL,
    
    endereco    VARCHAR(30),
    bairro      VARCHAR(20),
    cidade      VARCHAR(23),
    uf          VARCHAR(2),
    cep         VARCHAR(9),
    
    CONSTRAINT ck_cliente_cep CHECK (REGEXP_LIKE(cep, '^[0-9]{5}-[0-9]{3}$')),
    
    CONSTRAINT ck_cliente_status CHECK (status IN ('ATIVO','INATIVO')),
    
    CONSTRAINT fk_cliente_condicao_pag FOREIGN KEY (condicao_id)
        REFERENCES condicoes_pagamento (condicao_id)
)
NCM
CREATE TABLE ncms (
    ncm_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR2(10) NOT NULL,
    descricao VARCHAR2(200)
);
UNIDADE
CREATE TABLE unidades (
    unidade_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sigla VARCHAR2(10) NOT NULL,
    descricao VARCHAR2(50)
);
PRODUTO
CREATE TABLE produtos (
    produto_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao  VARCHAR2(100) NOT NULL,
    ncm_id     NUMBER NOT NULL,
    unidade_id NUMBER NOT NULL,
    ativo      CHAR(1) DEFAULT 'S',
    
    CONSTRAINT fk_produto_ncm FOREIGN KEY (ncm_id)
        REFERENCES ncms (ncm_id),

    CONSTRAINT fk_produto_unidade FOREIGN KEY (unidade_id)
        REFERENCES unidades (unidade_id)
);
PRECO / CUSTO
CREATE TABLE produtos_precos (
    preco_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id NUMBER NOT NULL,
    custo      NUMBER(10,2),
    preco_venda NUMBER(10,2),
    data_inicio DATE DEFAULT SYSDATE,

    CONSTRAINT fk_preco_produto FOREIGN KEY (produto_id)
        REFERENCES produtos (produto_id)
);
ESTOQUE
CREATE TABLE estoque (
    estoque_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id NUMBER NOT NULL,
    quantidade NUMBER(10,2) DEFAULT 0,

    CONSTRAINT fk_estoque_produto FOREIGN KEY (produto_id)
        REFERENCES produtos (produto_id)
);
CAIXA
CREATE TABLE caixa (
    caixa_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR2(30) NOT NULL,
    turno      CHAR(1) DEFAULT 'N'
);

VENDA
CREATE TABLE vendas (
    venda_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id NUMBER NOT NULL,
    condicao_id NUMBER NOT NULL,
    data_venda DATE DEFAULT SYSDATE,
    valor_total NUMBER(12,2),
    data_fechamento DATE DEFAULT SYSDATE, /* se nao tem data de fehamento e um orcamento*/
    caixa_id NUMBER NOT NULL,

    CONSTRAINT fk_venda_cliente FOREIGN KEY (cliente_id)
        REFERENCES clientes (cliente_id),

    CONSTRAINT fk_venda_condicao FOREIGN KEY (condicao_id)
        REFERENCES condicoes_pagamento (condicao_id),

    CONSTRAINT fk_venda_caixa FOREIGN KEY (caixa_id)
        REFERENCES caixa (caixa_id)
);
ITEM DA VENDA
CREATE TABLE vendas_itens (
    item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venda_id NUMBER NOT NULL,
    produto_id NUMBER NOT NULL,
    quantidade NUMBER(10,2),
    valor_unitario NUMBER(10,2),
    valor_total NUMBER(12,2),

    CONSTRAINT fk_item_venda FOREIGN KEY (venda_id)
        REFERENCES vendas (venda_id),

    CONSTRAINT fk_item_produto FOREIGN KEY (produto_id)
        REFERENCES produtos (produto_id)
);
CREATE TABLE pedidos_venda_recebimento (
    recebimento_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caixa_id NUMBER NOT NULL,
    venda_id NUMBER NOT NULL,
    data_movimento DATE DEFAULT SYSDATE,
    valor NUMBER(12,2),

    CONSTRAINT fk_pedido_venda_rec_caixa FOREIGN KEY (caixa_id)
        REFERENCES caixa (caixa_id),
    CONSTRAINT fk_caixa_venda FOREIGN KEY (venda_id)
        REFERENCES vendas (venda_id)
);
FINANCEIRO
CREATE TABLE financeiro (
    financeiro_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venda_id NUMBER NOT NULL,
    parcela NUMBER,
    condicao_id NUMBER NOT NULL,	
    data_vencimento DATE,
    valor NUMBER(12,2),
    pago CHAR(1) DEFAULT 'N',

    CONSTRAINT fk_financeiro_venda FOREIGN KEY (venda_id)
        REFERENCES vendas (venda_id),
    CONSTRAINT fk_financeiro_condicao FOREIGN KEY (condicao_id)
        REFERENCES condicoes_pagamento (condicao_id)
);
